### PR TITLE
update to eleventy

### LINKED ISSUE #285: [BUG] Update eleventy
### Describe the bug

When trying to build the site locally with a file that hasn't been committed yet you will get an error.

This is fixed in 2.0.0-canary.13
https://github.com/11ty/eleventy/pull/2459 

### Version of gc-da11yn you are using

_No response_

### OS or Device: (e.g. iOS)

_No response_

### Browser (e.g. Chrome, Safari)

_No response_

### Version (e.g. 22)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawnthompson**
closes #285

### CODE REVIEW

**Comment by duboisp** [comment]
Had you run the eleventy upgrade helper to ensure there's no code adjustment required with this upgrade?

**Comment by shawnthompson** [comment]
> Had you run the eleventy upgrade helper to ensure there's no code adjustment required with this upgrade?

I ran it for when I went from 0.# to 1.x but not for 2. I forgot about it. I'll look into adding it today.

[11ty/eleventy-upgrade-help: Helper plugin when upgrading your Eleventy project to a new major version.](https://github.com/11ty/eleventy-upgrade-help)

**Comment by shawnthompson** [comment]
@duboisp I ran the helper and it found no errors. It did have warnings but it was for things it couldn't check so it suggested we check them ourselves. They are features we aren't currently using.

Eleventy does not suggest leaving the plugin in the project. Therefore I'm not committing it to the repo.

Thanks for suggesting it!

**Review by duboisp — APPROVED** [review]
Great, thanks @shawnthompson for checking.

I don't have any other issue/concern with this PR, let's merge it.

**Pull request merged**
