### PR TITLE
optimize office TOC include

### PR DESCRIPTION
**Pull request by shawnthompson**

### CODE REVIEW

**Comment by shawnthompson** [comment]
@duboisp have a look at this TOC and let me know your thoughts?

[In development - How to create accessible documents in Office 2016 - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-386--a11ycanada.netlify.app/en/how-to-create-accessible-documents-in-office-2016/)

I'm using `<ul class="wb-eqht-grd">` and the "office step classes" like you suggested and I also added `<small class="visible-xs-block visible-sm-block visible-md-block visible-lg-block">` to the in Office $version which seems to work to put it on it's own line like I was looking for.

@JulieBB23 let me know how you like the new look? I think we should repeat the TOC at the bottom of the pages as well.

Thoughts?

**Comment by JulieBB23** [comment]
hey so i was looking at the TOC, and because on the previous page we actually have a link for Office 2016 and one for 365, i would remove in the TOC the one that is not relevant. And I would suggest that instead we have a related link at the bottom or maybe at the start of the page that would bring them to the other version "landing page"

**Comment by shawnthompson** [comment]
@JulieBB23, what about to the other version of the same page? Should the Word 2016 page have a link to the 365 Word page?

If you agree, how should this be presented? Just a link on its own line at the top of the page?

I would suggest the top of the page because say someone lands on the 2016 version from the start and they are looking for the 365 one instead, I think it would be more findable at the top of the document.

**Comment by shawnthompson** [comment]
This is what it looks like:

image

I added a link to the other version below the Table of Content and repeated it all at the bottom of the page.

[In development - How to create accessible documents in Office 2016 - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-386--a11ycanada.netlify.app/en/how-to-create-accessible-documents-in-office-2016/)

**Comment by shawnthompson** [comment]
Add `class="stretched-link"`

[Utilities - Working examples - Web Experience Toolkit](https://wet-boew.github.io/v4.0-ci/demos/utility/utility-en.html#miscellaneous)

**Pull request merged**
