### PR TITLE
Tip sheets updated

### PR DESCRIPTION
**Pull request by ocelph**
## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
Added the tip sheets html code (all except the Excel tip sheet)

**General checklist / Liste de contrôle générale**
- [Done ] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR
- [Done ] Validate changes against WCAG for accessibility /// Valider les changements avec WCAG pour l'accessibilité
- [Done ] Ensure documentation is bilingual /// S'assurer que la documentation soit bilingue

### CODE REVIEW

**Comment by shawnthompson** [comment]
List of all the URLs:

https://deploy-preview-606--a11ycanada.netlify.app/en/tip-sheets-for-microsoft-office/
https://deploy-preview-606--a11ycanada.netlify.app/fr/fiches-de-conseils-pour-microsoft-office/
https://deploy-preview-606--a11ycanada.netlify.app/en/tip-sheet-microsoft-excel
https://deploy-preview-606--a11ycanada.netlify.app/en/tip-sheet-microsoft-powerpoint-Presentation
https://deploy-preview-606--a11ycanada.netlify.app/en/tip-sheet-microsoft-word
https://deploy-preview-606--a11ycanada.netlify.app/en/tip-sheet-outlook
https://deploy-preview-606--a11ycanada.netlify.app/fr/fiche-de-conseils-microsoft-excel
https://deploy-preview-606--a11ycanada.netlify.app/fr/fiche-de-conseils-microsoft-word
https://deploy-preview-606--a11ycanada.netlify.app/fr/fiche-de-conseils-outlook
https://deploy-preview-606--a11ycanada.netlify.app/fr/fiche-de-conseils-presentation-powerpoint-de-microsoft

**Comment by Syracopoulos** [comment]
image

**Comment by Syracopoulos** [comment]
image

**Comment by Syracopoulos** [comment]
Can you double check that Microsoft is always capitalized?
I am getting 404 errors for most of the French pages. Can you double check and I'll come back?

**Review by Syracopoulos — APPROVED** [review]

**Comment by shawnthompson** [comment]
@Syracopoulos: Are you going to add more descriptive text to the descriptions?

**Review by shawnthompson — CHANGES_REQUESTED** [review]
Please add more descriptive text to the description of each page

**Comment by Syracopoulos** [comment]
[Home page of tip sheets.docx](https://github.com/user-attachments/files/16732787/Home.page.of.tip.sheets.docx)

**Comment by Syracopoulos** [comment]
[Create document homepage.docx](https://github.com/user-attachments/files/16732840/Create.document.homepage.docx)

**Comment by Syracopoulos** [comment]
[PowerPoint Presentation.docx](https://github.com/user-attachments/files/16732853/PowerPoint.Presentation.docx)

**Comment by Syracopoulos** [comment]
[Word.docx](https://github.com/user-attachments/files/16732884/Word.docx)

**Comment by Syracopoulos** [comment]
[Outlook.docx](https://github.com/user-attachments/files/16732901/Outlook.docx)

**Comment by Syracopoulos** [comment]
[Create document homepage FR.docx](https://github.com/user-attachments/files/16753696/Create.document.homepage.FR.docx)
[Home page of tip sheets FR.docx](https://github.com/user-attachments/files/16753700/Home.page.of.tip.sheets.FR.docx)
[Outlook FR.docx](https://github.com/user-attachments/files/16753704/Outlook.FR.docx)
[PowerPoint FR.docx](https://github.com/user-attachments/files/16753706/PowerPoint.FR.docx)
[Word FR.docx](https://github.com/user-attachments/files/16753708/Word.FR.docx)

**Comment by shawnthompson** [comment]
Work moved over to new PR #629

**Pull request closed without merging**
