### PR TITLE
Updated posters for Designing accessible services

### PR DESCRIPTION
**Pull request by acev0010**
## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
New PDF posters replace the SSC branding with the Government of Canada branding. Some of the text on the website was also updated to match the text on the posters.

**Related issues / Requêtes associées**
relates to #263

### CODE REVIEW

**Comment by acev0010** [comment]
I just noticed I need to also update the PDF links in https://deploy-preview-331--a11ycanada.netlify.app/en/guides/ so I will make another commit shortly.

**Comment by shawnthompson** [comment]
I've requested to have the posters modified and send us the new ones with that match the headings.

They will attach them in the issue:

[Remove SSC branding from posters · Issue #263 · gc-da11yn/gc-da11yn.github.io](https://github.com/gc-da11yn/gc-da11yn.github.io/issues/263)

**Comment by acev0010** [comment]
- I added the commit with the updated poster.

- Also switched the order between ''spectre autistique'' and ''cognitif'' in the French version to match the order of the English version.

**Review by shawnthompson — APPROVED** [review]
Good work, thanks!

**Pull request merged**
