### PR TITLE
Add Markdown it packages to project

### LINKED ISSUE #288: [FEATURE] Add IDs to headings so that we can link to the heading/section directly
### Is your feature request related to a problem? Please describe.

I would like to link to specific sections. To do that, I look into the code, grab the ID and I add it to the URL like this: http://mywebsite.com#headingID

### Describe the solution you'd like

Please add IDs to the headings so that I can create direct links.

### Describe alternatives you've considered

_No response_

### Who shall do the work?

- [X] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Timeline

No, as soon as possible but not a fire emergency

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawnthompson**
closes #288

### CODE REVIEW

**Review by duboisp — CHANGES_REQUESTED** [review]
There is no actual example showing that the eleventy.js implementation work as expected of the 3 added libs.

I tried this page: https://deploy-preview-332--a11ycanada.netlify.app/en/about/ where I expected to see "ids" on the heading level 2 and there was none. Is the markdown-it-anchor 

Should be automatically applied on any *.md file?

Do you have an example in gc-da11yn where it used the "attrs" feature on a markdown file?

**Comment by shawnthompson** [comment]
Right now we are only using it for heading ID.

Test page would be [Digital Accessibility Toolkit project - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-332--a11ycanada.netlify.app/en/about/dat/)

``` html

<h2 id="purpose" tabindex="-1">Purpose</h2>

```

**Comment by shawnthompson** [comment]
> I tried this page: https://deploy-preview-332--a11ycanada.netlify.app/en/about/ where I expected to see "ids" on the heading level 2 and there was none. Is the markdown-it-anchor


The `h2` in this markdown page are in `html` not markdown.

**Comment by duboisp** [comment]
> > I tried this page: https://deploy-preview-332--a11ycanada.netlify.app/en/about/ where I expected to see "ids" on the heading level 2 and there was none. Is the markdown-it-anchor
> 
> The `h2` in this markdown page are in `html` not markdown.

🤦‍♂️ 

Je me suis laisser avoir par l'extension du fichier dans github. Je n'ai pas regarder son code source, désolé.

**Review by duboisp — APPROVED** [review]
I confirmed the new markdown plugin (markdown-it and markdown-it-anchor) do work via this test page https://deploy-preview-332--a11ycanada.netlify.app/en/about/dat/

I am going to assume the plugin markdown-it-attrs do work too as it follow the same implementation logic.

**Pull request merged**
