### PR TITLE
Added the markdown link checker plugin

### PR DESCRIPTION
**Pull request by acev0010**
## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?

Adds the markdown-link-checker plugin and development guides.

### CODE REVIEW

**Comment by shawnthompson** [comment]
This looks good but we aren't over yet.

Can we get it to only scan the md files in ./src/pages/ folder?

**Comment by acev0010** [comment]
> This looks good but we aren't over yet.
> 
> Can we get it to only scan the md files in ./src/pages/ folder?

Done

**Comment by shawnthompson** [comment]
Can we output the results in a broken-links.json file on the root and add that file to the .gitignore so it's not tracked?

**Comment by acev0010** [comment]
Changes have been applied:

- Links are now generated inside a 'broken-links.json' in the root directory
- Added the file in the .gitignore 
- Updated development guides in both English and French

**Pull request merged**
