### PR TITLE
Added automated a11y checker. Issue #73

### PR DESCRIPTION
**Pull request by Lorenzo767**
Added automated a11y checker using github actions and pa11y.

### CODE REVIEW

**Comment by shawnthompson** [comment]
Thanks @Lorenzo767. 

I'm wondering if we can run this also when building locally?

**Comment by Lorenzo767** [comment]
> Thanks @Lorenzo767.
> 
> I'm wondering if we can run this also when building locally?

I will look into that! 👍

**Comment by Lorenzo767** [comment]
The way I tested it using pa11y is by downloading it as a global package:

```npm install -g pa11y```

Then, using:

```pa11y --ignore "notice;warning" http//localhost:8080```

When I am running an instance locally.
This is explained here: https://webdesign.tutsplus.com/tutorials/web-accessibility-testing-via-the-command-line-with-pa11y--cms-34538 You can take out --ignore "notice;warning" if you do not want warnings only errors to be printed out.

**Comment by shawnthompson** [comment]
Add the script in the package.json file as a rpm script. `rpm run a11y`

**Comment by shawnthompson** [comment]
`npm i --save-dev pa11y`

**Comment by shawnthompson** [comment]
Stale pull request will create a new one when ready to add testing to our build process.

Thanks for all your work @Lorenzo767

**Pull request closed without merging**
