### PR TITLE
Fixed issue 272 and 276

### PR DESCRIPTION
**Pull request by kellyanne-lecuyer**
This pull request is a correction for issues 272 and 276.

### CODE REVIEW

**Review by duboisp — COMMENTED** [review]
Reviewed and the propose change look good.

**Comment by duboisp** [comment]
Here the direct link to the test pages for review of the pull request

* Change related to #272
  * [Find out how to make accessible digital forms](https://deploy-preview-282--a11ycanada.netlify.app/en/guides/improving-form-accessibility/)
  * [Améliorer l’accessibilité des formulaires](https://deploy-preview-282--a11ycanada.netlify.app/fr/guides/improving-form-accessibility/) 
* Change related to #276
  * [How to create accessible documents in Office 365](https://deploy-preview-282--a11ycanada.netlify.app/en/guides/office365/) 
  * [Comment créer des documents accessibles dans Office 365](https://deploy-preview-282--a11ycanada.netlify.app/fr/guides/office365/)

**Comment by duboisp** [comment]
@soniamarleau as requested, you can now review the following pages which should contain the link update you requested via the request #272.

* [Find out how to make accessible digital forms](https://deploy-preview-282--a11ycanada.netlify.app/en/guides/improving-form-accessibility/)
* [Améliorer l’accessibilité des formulaires](https://deploy-preview-282--a11ycanada.netlify.app/fr/guides/improving-form-accessibility/)

**Comment by shawnthompson** [comment]
Closes #272 
Closes #276

**Review by shawnthompson — APPROVED** [review]
Looks good, let's merge.

**Pull request merged**
