### PR TITLE
Added pages for hosting accessible events in EN and FR

### PR DESCRIPTION
**Pull request by DhruvPatel2502**
_(Pick the language of your choice to fill out the following information. / Choisissez la langue de votre choix pour remplir l'information ci-dessous.)_

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
A clear and concise description of what the code of this PR accomplishes. /// Une description claire et concise de ce que le code de cette PR accompli.

## Additional information (optional) / Information additionnelle (optionel)

**General checklist / Liste de contrôle générale**
Make your own list for the purpose of your Pull request. /// Faites votre propre liste en fonction des besoins de votre demande « pull ».

- [ ] Create/update documentation /// Créer/mettre à jour la documentation
- [ ] Build and test PR's code /// Rouler le script de compilation et tester le code de la PR
- [ ] Validate changes against WCAG for accessibility /// Valider les changements avec WCAG pour l'accessibilité
- [ ] Ensure documentation is bilingual /// S'assurer que la documentation soit bilingue

**Related issues / Requêtes associées**
List issues that are being closed or worked on with this pull request i.e. Closes #8941 /// Listez les autres requêtes (« issues » ou PR) qui sont fermées ou traitées avec cette demande de retrait ex. : Closes #8941

**Screenshots / Captures d'écrans**
If applicable, add screenshots to help demonstrate what this PR does. /// Si applicable, ajoutez des captures d'écran pour aider à démontrer ce que cette PR fait.

### CODE REVIEW

**Comment by shawnthompson** [comment]
Preview page:
[In development - Best practices for accessible virtual events - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-422--a11ycanada.netlify.app/en/best-practices-for-accessible-virtual-events/)

**Review by shawnthompson — CHANGES_REQUESTED** [review]
Change all the # h1 to ## h2 and the sub heading accordingly?

Add heading to the Table of content titles "On this page" as defined on [In-page table of contents - Canada.ca](https://wet-boew.github.io/GCWeb/components/gc-toc/toc-en.html).

Limit the table of content to only the level 2 headings

**Comment by shawnthompson** [comment]
Ready for you to review @kimviens 

[Best practices for accessible virtual events](https://deploy-preview-422--a11ycanada.netlify.app/en/best-practices-for-accessible-virtual-events/)

**Comment by kimviens** [comment]
I did a review and it looks good as a stable start. For sure it does not contain functionalities that would make it more consumable. I still think expand/summary components with a button to "expand all/collapse all" would make a huge difference. We can only build up from here. I think this task is concluded.

**Comment by shawnthompson** [comment]
Shouldn't this be a topic page and not a third level page?

Third level pages collect all the topic pages with specific `tags`. [Eleventy](https://www.11ty.dev/) uses the keyword `tags` to group common pages with the same `tags`. We could later on try to create collections with custom keywords, like using `topic` instead of `tags` but right now we are using the out of the box keyword.

We have a page one level up that holds all information on accessible meetings and events.

[In development - Host a meetings and events - Digital Accessibility Toolkit / Sharing space](https://deploy-preview-422--a11ycanada.netlify.app/en/host-a-meetings-and-events/).

On that page so the subject would be `howTos` and the tags would be `hostMeetingsAndEvents` based on the table found in issue #319?

We have certain third level pages that are just content but we would like to group them as much as possible in collection first. Which was decided early on in the project at content task force meetings.

I hope this makes this clearer. I'd like to eventually write up documentation of all this.

Thank you all for your help 

cc: @JulieBB23 @kimviens

**Comment by shawnthompson** [comment]
I'll merge this request a fix anything in another PR to come.

**Pull request merged**
